run:
  tests: true
  skip-dirs:
    - internal/cmd

linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gomnd
    - lll
    - nakedret
    - wsl