// Code generated by mockery v1.0.0. DO NOT EDIT.

package scanner

import migration "github.com/riabininkf/go-migrator/pkg/migration"
import mock "github.com/stretchr/testify/mock"

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

// Scan provides a mock function with given fields: path
func (_m *MockScanner) Scan(path string) ([]migration.Migration, error) {
	ret := _m.Called(path)

	var r0 []migration.Migration
	if rf, ok := ret.Get(0).(func(string) []migration.Migration); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]migration.Migration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
