// Code generated by mockery v1.0.0. DO NOT EDIT.

package migration

import mock "github.com/stretchr/testify/mock"

// MockMigration is an autogenerated mock type for the Migration type
type MockMigration struct {
	mock.Mock
}

// Down provides a mock function with given fields:
func (_m *MockMigration) Down() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *MockMigration) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Up provides a mock function with given fields:
func (_m *MockMigration) Up() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
